### PR TITLE
#154715725 reviews and ratings

### PR DESCRIPTION
**Pull request by RachelAbaniwo**
#### What does this PR do?
adds reviews and ratings functionality to products and shops

#### Description of Task to be completed?
- install react-stars to enable users rate a product
- create the productrating.js component
- create the productreview.js component
- add product rating and product review component to simple.js
- add shop reviews to subscriptions
- refactor product rating controller to match screen style
- add class names to product-review controller and remove inline styling
- add rate-shop button to tag.js file
- add shop-reviews register.js file
- add client index.js file for shop
- add component index.js file for shop
- add shop-rating controller
- add shop-review controller
- add template files for shop ratings and reviews

#### How should this be manually tested?
- navigate to the product page to add product reviews and ratings, the product shop is displayed 
  and rate-shop button is also displayed, clicking the button redirects to a shop review page.

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#154715725

#### Screenshots (if appropriate)
screen shot 2018-02-06 at 5 19 56 pm

screen shot 2018-02-06 at 5 20 28 pm

#### Questions:
N/A

### CODE REVIEW

**Review by Victoradukwu — COMMENTED** [review]
I like that you observe good PR naming and description conventions and for sticking to es6 standards.

**Review by sannytee — COMMENTED** [review]
Good work raising this P.R. It's well documented but you should avoid using '_'.

**Review by michaelogala — CHANGES_REQUESTED** [review]
The code works but there is a lot of duplication. `Review` and `Rating` can be standalone models, then they can be applied to any other model. Say we need to be able to rate customers in the future, would we then create  `CustomerReview` and `CustomerRating` models also? The concept that can help you DRY up this code is called `Polymorphic Relationships/Associations`. Look it up and refactor this code.

**Review by michaelogala — CHANGES_REQUESTED** [review]
There is still some refactoring to do. You can have just one `Review` component and one `Rating` component and reuse both for Shops and Products. Think about it.

**Review by michaelogala — APPROVED** [review]

**Pull request merged**
